### ISSUE TITLE
[Feature] Add full package path to class filename

### ISSUE THREAD

**Issue by FarisR99** [chirag-ji/Jacotura#13]
For GitLab code coverage visualization to work, it looks like the class filename property in Cobertura report must include the full path of the package, e.g. rather than "TestClass.java" it would be "com/some/test/TestClass.java". I've previously used a python script from https://gitlab.com/haynes/jacoco2cobertura to do this and it generates a report that can be used in GitLab, but I'm trying to migrate to a  Gradle plugin that does this, and this project seems like the best choice.

Can we please get a new property/setting to enable this?

**Comment by chirag-ji** [comment]
Hey @FarisR99.

Thanks for suggesting the improvements.

Just drafted a new release versioned `1.1.0` introducing the requested functionality.

Will be available shortly via gradle plugin portal.

Thanks

**Comment by chirag-ji** [comment]
Release versioned `1.1.0` out now.

[Plugin Portal Link](https://plugins.gradle.org/plugin/io.github.chiragji.jacotura)

**Comment by FarisR99** [comment]
Thanks!
