### ISSUE TITLE
Method line rate is 0

### ISSUE THREAD

**Issue by JohnKratos33** [chirag-ji/Jacotura#28]
**Describe the bug**
All my methods branch rate, complexity and line rate is 0.0

**Environment**
 - Java Version [e.g. JDK 1.8] JDK 17
 - OS [e.g. Linux / Windows] Linux

**Expected behavior**
Line rate is correct at the least

**Additional context**
Looking at the source code, I think computeRates for the method is missing. It is called for class, package etc but not method

Great project by the way

**Comment by chirag-ji** [comment]
Hi @JohnKratos33,

Thanks for letting me know.

Let me fix it quickly

**Comment by chirag-ji** [comment]
Hi @JohnKratos33,

A release `1.1.2` has been created and will be available soon via plugin portal.

Thanks for improving the project.
